36 markdown
totegamma/concurrent-web pull request #57
Opened 2023-05-06 06:19 UTC by jojo3926

Heading要素のmarginがやけに大きい問題は解決しましたが、headingが二行連続すると行間に空白の行が挿入される現象が発生しました。よくわからないのでここに投げておきます。

2023-05-06 06:32 UTC, totegamma commented
もしよかったらコンフリクト治せますか？難しそうだったらこっちでやります！

2023-05-06 07:03 UTC, jojo3926 commented
なおしました

2023-05-06 12:15 UTC, totegamma requested changes
Conflict解消ありがとうございます！

現状のコードだと、themes.tsの中にテーマ定義以外のものが入っているためsettingsタブを開くとクラッシュしてしまいます。コードコメントを追加したのでそこを修正してもらえると嬉しいです！！！！

2023-05-06 12:15 UTC, totegamma commented on src/components/Tweet.tsx
> +                                <ThemeProvider theme={Themes}>
ここでテーマの再代入をするのは避けたいです。
また、変数'Themes'は、テーマの集合であるため、これをそのまま渡すのは不適切かもしれません。
Themes.tsの方を更新して、この行(とclose行)は削除で良いと思います。

2023-05-06 12:15 UTC, totegamma commented on src/themes.ts
> +    typography: {
themes.tsはテーマの集合なので、この書き方だと「typographyという名前のテーマ」を定義していることになってしまいます。
そのため、現状のコミットだと設定ページ(テーマ一覧が表示される)をクリックするとクラッシュしてしまいます。

このtypographyの設定内容自体は素晴らしいと思うので、このブロックを現状実装されているすべてのテーマにそれぞれ代入してもらえると嬉しいです！

例えば、
```
export const Themes = {
    red: {
        palette: {
            primary: {
                main: '#E0576F'
            },
            background: {
                default: '#C74E64'
            }

        },
        typography: {
            h1: {
                fontSize: 32
            },
            h2: {
                fontSize: 24
            },
            h3: {
                fontSize: 19.2
            },
            h4: {
                fontSize: 16
            },
            h5: {
                fontSize: 12.8
            },
            h6: {
                fontSize: 11.2
            }
        }
    },
    blue: {...
```
という感じです。

2023-05-07 05:32 UTC, jojo3926 commented
修正しました。

2023-05-07 05:43 UTC, jojo3926 commented
フォントがほそくなってしまった

2023-05-07 06:22 UTC, totegamma requested changes
ありがとうございます！！！！完璧です。
最後未使用のものをクリーンアップしていただけたらマージしようと思います。

2023-05-07 06:22 UTC, totegamma commented on src/components/Tweet.tsx
> +    ThemeProvider,
未使用のThemeProviderのimportを削除
```suggestion
```

2023-05-07 06:22 UTC, totegamma commented on src/components/Tweet.tsx
> +import { Themes } from '../themes'
未使用のThemesのimportを削除
```suggestion
```

2023-05-07 06:42 UTC, totegamma approved these changes
LGTM✨✨✨✨✨✨

2023-05-07 06:42 UTC, merged